// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"
	"time"

	"casinoDemo/api/casino/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/participate",
				Handler: ParticipateHandler(serverCtx),
			},
		},
		rest.WithTimeout(3000*time.Millisecond),
	)
}
