// Code generated by goctl. DO NOT EDIT.
package types

type ClaimBonusReq struct {
	Address  string `json:"address"`
	BlockSeq int64  `json:"blockSeq"`
}

type ClaimBonusResp struct {
}

type ParticipateReq struct {
	Value    int64  `json:"value"`
	Address  string `json:"address"`
	BlockSeq int64  `json:"blockSeq"`
}

type ParticipateResp struct {
}
